language: ruby
rvm:
- 2.3
before_install:
- gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
- gem install bundler -v '< 2'
install: bundle install
script: gem build facebookbusiness.gemspec
deploy:
  provider: rubygems
  api_key:
    secure: a0LEmoM6WagYxCadbQw4j6JRKfj2NoNMd7izWTJFF1V2pF66MciEo2QwSsCNXbfmmy7lhNcVYSc1xUglvfqJJZorfkrPkHDzydDHYo50Hz+qvmABCUjg83E69cK3LSsAyQ6oX7OiJMkZxIL6buqyKQ5qd9m64hoSS84HVwRywuE=
  gem: facebookbusiness
  on:
    # tags: true
    all_branches: true
    repo: facebook/facebook-ruby-business-sdk
